### ISSUE TITLE
Issues with DF Active and Auto Anim

### ISSUE THREAD

**Issue by Xerephus** [diwako/foundry-cyberpunk-red-core-additions#19]
Doesn't seem to be working right ATM, could it be an issue with them upgrading to Ver 11?

**Comment by diwako** [comment]
Just tried it out, still works in my game. To my knowledge DF active lights will not receiving updates anymore, autoanimations still should. I updated both modules just in case on my end, just to see they were already up to date on my end.

It could be that it does not show on single shots due to latency delay and how DF active light works. Basically, Active lights uses the server tick rate to animate the light source. Due to latency it could be that the light source is created after the keyframe should be showing the light.

An almost surefire way to check is to use autofire, as it shoots 10 times it should be showing up unless you have a latency of multiple seconds.

**Comment by Xerephus** [comment]
Just tested it on my end and with Automated, DF, and the JBSA Patreon. Autofire still won't muzzle flash for me or do the traces like on the preview shown.

Maybe I have something set up wrong?

**Comment by diwako** [comment]
Make sure you have the setting enabled in the modules settings. It might be disabled.
Can you check if anything is in the clients console which might indicate some issue or error?

**Comment by Xerephus** [comment]
I have it enabled an no errors come up when an attack is made. No sound is played either but the hit animation is played.

**Comment by diwako** [comment]
mind taking a screenshot of the console.
first clear the console, then fire a shot or a full auto attack. take screenshot

make sure that automated animation and df active lights are enabled, and that an attach animation from automated animations is being played.

**Comment by Orphansmith** [comment]
Just tested this out as well, and it doesn't work for me either.
![image](https://github.com/diwako/foundry-cyberpunk-red-core-additions/assets/69684534/82bae034-8840-4918-90d2-bde349484b58)
(Ignore the bottom two messages, that was when I had to change the window size to take the screenshot).
I see messages for rendering the roll dialogue, the array for the dice, and outputting the chat message. I see the basic hit animation (or miss in the case of missing), but the lights and bullet animations aren't working.

I have all modules installed, the setting to show the animations is turned on, I tried using auto-fire on an assault rifle and the animations just aren't showing up. I can see the hit and miss animations, and my custom sound goes off. Basically everything but this, https://github.com/diwako/foundry-cyberpunk-red-core-additions/raw/master/images/dfLights.gif

**Comment by diwako** [comment]
Hm, weird. then lets try to reconstruct the conditions for it to work.

I will be using some mook with an assault rifle, using `Rifle (basic)` as ammunition. You need at least one additional token to the mood in the scene. Make sure that the scene is set up so ambient light works and can take effect, might just up the darkness value for that.

First of check if the modules are active. We need 3 modules active.
- Automated Animations
- DF Active Lights
- JB2A (patron version optional) (needed for Automated Animations)

Then we check this ammunition type has an effect configured for the module `Automated animations`
Here when opening the ammunition item and clicking the `A-A` button in the header
![image](https://github.com/diwako/foundry-cyberpunk-red-core-additions/assets/8259498/cf255cd9-90fd-4a48-b32d-c2b80bb1c384)

The config looks like this within the Automated Animations global config.
![image](https://github.com/diwako/foundry-cyberpunk-red-core-additions/assets/8259498/004aa107-3830-4481-8d9c-6200baaa0ce0)

After that, we select the second token as target, and for easier time spotting the ambient light, choose to autofire or suppressive fire.

https://www.youtube.com/watch?v=0-AHLqO6wOs

**Comment by Orphansmith** [comment]
So, there's possible two issues for me.

1) The AA menu doesn't have any Cyberpunk RED specific animations, it's all D&D stuff. However, there are settings for Cyberpunk under Settings for A-A (Enable Autoamtic Repeats, Use forceMiss, etc).
![image](https://github.com/diwako/foundry-cyberpunk-red-core-additions/assets/69684534/4d751780-965f-4cb4-9516-eaaa452876f1)
![image](https://github.com/diwako/foundry-cyberpunk-red-core-additions/assets/69684534/f70e109c-958f-49bb-bacf-d7922abdd1a9)
2) I'm running Forge-VTT on version 10, though I think it should default to the last working version for any version 10 release?

**Comment by diwako** [comment]
1. A-A does not ship with cyberpunk configs. you need to make them yourself or find someone who shares their configs
2. This module at least supports both v10 and v11

**Comment by Orphansmith** [comment]
I see. I went in and created a default rifle animation to test, and the lighting effects still won't go off, although the animations work now!

The following error is all that shows up in the console after test firing,
`commons.js:1703 Error: You are accessing the CPRCombatant#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at CPRCombatant._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at CPRCombatant.new_getToken (floating-combat-toolbox.js:285:26)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Combatant.prototype.token#getter (libWrapper-wrapper.js:364:19)
    at hooks.mjs:261:49
    at EmbeddedCollection.some (commons.js:3378:22)
    at Object.fn (hooks.mjs:261:37)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at ClientDatabaseBackend.callback (foundry.js:12824:13)
    at foundry.js:12804:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12804:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12672:17)
    at async TokenDocument.updateDocuments (commons.js:6153:23)
    at async TokenDocument.update (commons.js:6250:23)
    at async TokenDocument.updateActorEmbeddedDocuments (foundry.js:22208:5)
    at async Proxy.updateDocuments (commons.js:6153:23)`

**Comment by Orphansmith** [comment]
Nevermind, it's working now?

Does seem to be an issue with the delay.

**Comment by diwako** [comment]
Try autofire, there is some server <-> client delay, i tried to compensate for this but it is a bit hard to do.

**Comment by Orphansmith** [comment]
Yeah, no worries. At least it's working!

**Comment by diwako** [comment]
I will be closing this issue now. I know that I answered a bunch of things but not to the original creator of this issue, still it has a bunch of info which can be used to try out how things work
