### ISSUE TITLE
Missing DVs

### ISSUE THREAD

**Issue by araeloth** [diwako/foundry-cyberpunk-red-core-additions#22]
Looks like the shotgun and grenade launcher DVs aren't available. Is there anything in the works, or a fix I can try?

**Comment by diwako** [comment]
That is an issue of the system. The module only reads what is there. You could however, import the toll table the DVs are in and edit them. The module *should* check if there is an imported roll table of the matching name is present before it looks into the system configured compendium.

**Comment by araeloth** [comment]
I see, so create my own DV table that the module can reference the same way it does other weapons. Would there be a particular naming convention to follow, or anything in particular outside of creating a "Shotgun DV" table?

**Comment by araeloth** [comment]
Gotcha, so I just have to work on getting a table set up. Appreciate it, and love the Mod!
